import Foundation

extension AppSettings {
    struct TextSettings: Codable, Equatable {
        var version: Int = 0
        var systemName: AppSettingName = .text
        var tags: [String] = []
//        let rightToLeft: Bool = false
//        let isHebrew: Bool
//        let arpalusHelpUrl: String
//        let updateIsAvailable: String
//        let checkingConnection: String
//        let wifiNotAvailable: String
//        let loginIn: String
//        let loginFirstTimeWhenOffline: String
//        let loginFirstRunNoInternet: String
//        let loginFailed: String
//        let loginFailedNoDiskSpace: String
//        let loginOktaButton: String
//        let loginEmail: String
//        let loginEmailPlaceholder: String
//        let loginPassword: String
//        let loginPasswordPlaceholder: String
//        let loginForgotPassword: String
//        let loginButton: String
//        let pendingUploads: String
//        let needHelp: String
//        let updateLabel: String
//        let versionAlert: String
//        let updatingInProgress: String
//        let notificationHeader: String
//        let makeSureWiFi: String
//        let settingsVersion: String
//        let settingsHeader: String
//        let settingsUser: String
//        let settingsPlanograms: String
//        let settingsPage: String
//        let updateSettingsButton: String
//        let logoutButton: String
//        let copyButton: String
//        let clearButton: String
//        let latestUpdate: String
//        let uploadTxt: String
//        let uploadFailed: String
//        let uploadingInProgress: String
//        let uploadBatch: String
//        let uploadingImage: String
//        let memoryUsage: String
//        let settingsDisconnected: String
//        let homeHey: String
//        let homeGuest: String
//        let homeFarFromLocation: String
//        let homeStoreChangeButton: String
//        let homeStoreSubtitle: String
//        let homeTaskSubtitle: String
//        let homeDisplaySubtitle: String
//        let homeFirstSession: String
//        let homeMissingModels: String
//        let homeLowMemory: String
//        let homeFirstChooseStore: String
//        let homeLastVisitedPrefix: String
//        let homeLocationMissingWarning: String
//        let homeTaskMissingWarning: String
//        let homeDisplayMissingWarning: String
//        let homeGPSMissingWarning: String
//        let homeMetricLastScan: String
//        let startScanButton: String
//        let arScanButtonStart: String
//        let arScanButtonShelves: String
//        let arScanButtonFinish: String
//        let arScanButtonFinishSegment: String
//        let arNextSegmentButton: String
//        let changePogButton: String
//        let savedScanNamePrefix: String
//        let scanProcessingDone: String
//        let cancelFinishScanPog: String
//        let cancelFinishScanCount: String
//        let planogramTitle: String
//        let realogramTitle: String
//        let instructionsHeader: String
//        let instructionsDetails: String
//        let tutorialHeaderText: String
//        let tutorialinstructionText: String
//        let userTooClose: String
//        let userTooFar: String
//        let userAngleTooSharp: String
//        let userMotionTooFast: String
//        let hurrayTitle: String
//        let hurrayDescription: String
//        let reportStoreNotSelected: String
//        let reportPlanogram: String
//        let reportHeader: String
//        let reportOutOfStock: String
//        let reportSomeMissing: String
//        let reportInStock: String
//        let reportSurplus: String
//        let reportOOS: String
//        let reportASO: String
//        let reportPOG: String
//        let reportVoids: String
//        let lastScanTitle: String
//        let reportDefaultCategory: String
//        let reportDefaultSupplier: String
//        let reportSegment: String
//        let reportProducts: String
//        let questionerSelect: String
//        let questionerSkip: String
//        let storeChooseButton: String
//        let storesHeader: String
//        let locationSelectStore: String
//        let locationSelectTask: String
//        let locationSelectDisplay: String
//        let planogramStoreNotSelected: String
//        let PlanogramPageHeader: String
//        let preparingReport: String
//        let finishingScan: String
//        let resetPasswordButton: String
//        let resetPasswordTitle: String
//        let userSettingsTitle: String
//        let resetPasswordSubtitle: String
//        let sendButtonTitle: String
//        let resetPasswordErrorNotificationFormat: String
//        let resetPasswordActionUnsuccessful: String
//        let planogramIDText: String
//        let notificationUploadNoInternetTitle: String
//        let notificationUploadNoInternetText: String
//        let notificationUploadQuitTitle: String
//        let notificationUploadQuitText: String
//        let notificationUploadingTitle: String
//        let notificationUploadingText: String
//        let notificationUploadedTitle: String
//        let notificationUploadedText: String
//        let tutorialPublicVideoUrl: String
//        let tutorialLoadingVideoNotification: String
//        let tutorialLoadingVideoError: String
//        let tutorialLoadingSlidesNotification: String
//        let tutorialLoadingSlidesError: String
//        let tutorialLoadingInternetError: String
//        let tutorialSeeSlidesButton: String
//        let tutorialSeeVideoButton: String
//        let tutorialOpenHelpButton: String
//        let endScanTooManyTitle: String
//        let endScanTooManySubtitle: String
//        let endScanTooManyDeleteButton: String
//        let endScanNotEnoughDataTitle: String
//        let endScanNotEnoughDataSubtitle: String
//        let endScanEndScanTitle: String
//        let endScanEndScanSubtitle: String
//        let endScanImageLimitTitle: String
//        let endScanImageLimitSubtitle: String
//        let endScanManualSaveButton: String
//        let endScanManualAskDeleteButton: String
//        let endScanManualAreYouSureNoButton: String
//        let endScanManualAreYouSureDeleteButton: String
    }
}
