default_platform(:ios)

before_all do
  match(type: 'appstore', readonly: false)
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ArpalusSample.xcodeproj", build_number: latest_testflight_build_number)
    build_app(scheme: "ArpalusSample")
    upload_to_testflight
  end
end
